edbentley/replay

packages/replay-web/src/__tests__/inputs.test.ts, packages/replay-web/src/draw.ts, packages/replay-web/src/index.ts, packages/replay-web/src/input.ts
- Game focus
- Set game focus when clicked inside game
- Only register key inputs when game is focussed
- Don't scroll when focussed, fixes https://github.com/edbentley/replay/issues/1
- Return `cleanup` function in `renderCanvas`
- Fix black bars issue on small devices
- Allow override of viewport width and height in `renderCanvas`
=> Web: focus, cleanup and view size

dev-game/src/PlayStage.ts, dev-game/src/PosLogger.ts, dev-game/src/__tests__/game.test.ts, packages/replay-starter-js/src/__tests__/game.test.js, packages/replay-starter-ts/src/__tests__/game.test.ts, packages/replay-test/src/__tests__/replay-test.test.ts, packages/replay-test/src/index.ts, packages/replay-web/src/index.ts, packages/replay-web/src/input.ts, website/docs/device.md, website/docs/test.md, website/docs/tutorial/20.md, website/docs/tutorial/21.md, website/docs/web.md, website/src/pages/tutorial/21.js, website/src/tutorial/20/js/__tests__/game.test.js, website/src/tutorial/20/ts/__tests__/game.test.ts, website/src/tutorial/21/js/__tests__/game.test.js, website/src/tutorial/21/ts/__tests__/game.test.ts
- (Breaking change) Renames `testGame` to `testSprite` and passes in `gameProps` separately
- Allow adjusting pointer (x, y) coordinates in tests
=> Testing for Sprites

packages/replay-test/src/__tests__/replay-test.test.ts, packages/replay-test/src/index.ts
Fixes error suppression inside jumpToFrame when there is one. Instead of always throwing the `Timeout of 1000 gameplay seconds reached on jumpToFrame` error, it will throw the last caught error if there is one.
=> throw correct error inside jumpToFrame

dev-game/jest.config.js, dev-game/src/__tests__/game.test.ts, packages/replay-starter-js/jest.config.js, packages/replay-starter-js/src/__tests__/game.test.js, packages/replay-starter-ts/jest.config.js, packages/replay-starter-ts/src/__tests__/game.test.ts, packages/replay-test/jest.config.js, packages/replay-test/src/__tests__/replay-test.test.ts, packages/replay-test/src/index.ts, website/docs/test.md, website/docs/tutorial/20.md, website/src/tutorial/20/js/__tests__/game.test.js, website/src/tutorial/20/ts/__tests__/game.test.ts, website/src/tutorial/21/js/__tests__/game.test.js, website/src/tutorial/21/ts/__tests__/game.test.ts, website/src/tutorial/22/js/src/__tests__/game.test.js, website/src/tutorial/22/ts/src/__tests__/game.test.ts
**Breaking changes.** This changes `jumpToFrame` to be async to avoid blocking the event loop. It also stops `getByText` throwing errors.
=> Test blocking and errors

packages/replay-core/src/core.ts
Sometimes you'll accidentally return an `undefined` element in the `render` function. This is not officially supported, but the resulting error was hard to debug, so we can just treat `undefined` the same as `null`.
=> Filter out undefined Sprites

packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/core.ts, packages/replay-core/src/sprite.ts, website/docs/sprites.md
This allows `state` to be accessed from the `init` method in callbacks that rely on it.
e.g:
```js
init({ getState }) {
function onLogin() {
console.log("Successful login", getState().name);
}
Backend.login(onLogin);
return { name: "X" };
}
```
=> Add getState to Sprite init method

packages/replay-test/src/__tests__/replay-test.test.ts, packages/replay-test/src/index.ts, website/docs/test.md
**Breaking Change**. This reduces the default number of frames `jumpToFrame` runs for to avoid tests taking a long time to fail. But the setting can be overridden through the `maxFrames` argument.
=> Update number of frames run in jumpToFrame

dev-game/src/index.ts, packages/replay-web/src/index.ts, packages/replay-web/src/input.ts
This handles games being scrolled - e.g. on iOS, the keyboard can scroll the game up to keep the text input visible.
=> Handle scroll offset for pointer position

packages/replay-swift/Replay/Sources/Replay/ReplayViewController.swift, packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift, packages/replay-web/src/index.ts
This PR:
- (Web) Stop audio context from resuming when the page is hidden
- (Swift) Disables undesirable haptic feedback on long presses
- (Swift) Greys out home bar and requires two swipes to use
=> Audio on page hidden, haptic feedback, home bar

packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/core.ts
For https://github.com/edbentley/replay/issues/57
Managed to find a way to detect duplicate Sprite IDs with minimal runtime impact.
=> Throw error on duplicate Sprite IDs

packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift
This fixes a regression from #60 where text inputs couldn't be tapped on iOS. Don't ask me why this works. 🤷‍♂️
=> Fix pressing on iOS text input regression

packages/replay-web/src/index.ts
Previously `device.inputs.keysJustPressed` would flicker on and off for a key when held down, due to keyboards repeating keys when held down. This change disables that, which I think is preferred for building games.
=> Web: Ignore repeat keys held down

packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/device.ts, packages/replay-test/src/__tests__/replay-test.test.ts, packages/replay-test/src/index.ts, packages/replay-web/src/device.ts, website/docs/device.md
**Breaking change**. This refactors `audio("filename").play` to allow more fields to passed in.
Also adds a new field `overwrite` to ensure the same sound file can't be played twice (e.g. background music). Previously trying to pause and play the sound in one frame would not work.
=> Update audio play and include overwrite field

packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/core.ts
Previously calling `updateState` within another `updateState` would not ever get called. This PR ensures all nested `updateState` calls will run.
=> Support nested updateState calls

packages/replay-swift/Replay/Sources/Replay/ReplayStorageProvider.swift, packages/replay-swift/Replay/Tests/ReplayTests/ReplayTests.swift, packages/replay-swift/src/renderCanvas.ts
Previously we were using `UserDefaults` on iOS to store locally, but this has a [4 MB limit on recent iOS versions](https://developer.apple.com/forums/thread/121527).
This PR uses the app's Documents folder to persist files instead and shouldn't have any limits.
=> Use Documents files for iOS storage

packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/core.ts
Adds check for duplicate ids in the first frame of Sprites, and ensures checks are also made in Pure Sprites.
=> Duplicate Sprite ID in first frame

packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/device.ts
Handles an edge case where a Sprite is removed and then shown again, before `preloadFiles` finishes.
=> preloadFiles unmounted then remounted

packages/replay-web/src/device.ts
This avoids a bug where audio sometimes doesn't pause.
=> Remove onended when pause audio

packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/core.ts, packages/replay-core/src/sprite.ts, packages/replay-test/src/index.ts, website/docs/sprites.md
The `cleanup` method is called when a Sprite is unmounted. It's not required for vanilla Replay, but if you're using some external libraries which need cleaning up it's useful.
=> Add cleanup Sprite method

packages/replay-swift/Replay/Sources/Replay/ReplayAlerter.swift, packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift, packages/replay-swift/src/renderCanvas.ts
This avoids blocking the main thread on iOS during alerts.
=> Use bridge for alerts on iOS

packages/replay-web/src/device.ts
Ideally we shouldn't need this, but I have seen it on iOS 12 (and possibly iOS 13, need to confirm). Latest iOS doesn't have this problem.
=> Fix web audio error on older Safari

packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift, packages/replay-web/src/index.ts
- Reload the WebView when memory usage forces it to close. This crash often happens on app relaunch so this should make it less obvious.
- Avoid timestamp bug of `loop` being called just before page is visible (and giving uncompensated time value). This was causing the game to freeze a long time when minimised and reopened.
=> Swift: Avoid WebView crashes on relaunch

packages/replay-swift/src/renderCanvas.ts
- Supports `console.error` and other methods too
- Supports multiple arguments
=> Swift: print other console methods

packages/replay-android/android-library/replay-android/src/main/java/com/replay/android/ReplayActivity.kt, packages/replay-android/android-library/replay-android/src/main/java/com/replay/android/WebAppInterface.kt, packages/replay-swift/Replay/Sources/Replay/ReplayStorageProvider.swift, packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift
This is to avoid blocking the main thread (causing visible lag) on mobile when saving. Seems to work well on Android, but still noticeable lag spike on iOS.
=> Use background threads for storage

packages/replay-swift/Replay/Sources/Replay/ReplayViewController.swift, packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift
Can be useful for displaying error message or logging crashes.
=> Swift: Allow overriding JS crashes

website/docs/text-input.md
This quick fix helps update the docs regarding `TextInput` so that `nativeSpriteMap` is reflected as the key for which the existing map should be the value.
=> Fix docs with respect to nativeSpriteMap mapping for TextInput

packages/replay-core/src/__benchmarks__/utils.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/device.ts, packages/replay-test/src/index.ts, packages/replay-web/jest-setup.js, packages/replay-web/src/__tests__/device.test.ts, packages/replay-web/src/device.ts, packages/replay-web/src/index.ts, website/docs/device.md
Provides a `globalAudio.volume` and `globalAudio.setVolume` in `device` to control the global volume level. Makes it easier for games to implement a volume slider.
=> Add property to set global volume

packages/replay-core/src/device.ts, packages/replay-web/src/index.ts
For replay-web, fixes an issue that holds up the game loop on alerts (and then time jumps when dismissed).
=> Web: Fix pausing game loops for alert
