edbentley/replay

packages/replay-swift/Replay/Sources/Replay/Draw.swift, packages/replay-swift/Replay/Sources/Replay/ReplayViewController.swift
- Handle unknown fonts better by still using the system font with the font size set
- Add option to hide status bar in `ReplayViewController`.
=> Swift: unknown fonts and status bar

packages/replay-web/src/draw.ts, packages/replay-web/src/index.ts
Fixes the white background size and cleanup function on `@replay/web`.
=> Web: white rect background and cleanup fix

packages/replay-web/src/index.ts, packages/replay-web/src/input.ts
This avoid the pointer remaining pressed when the pointer is dragged outside the view.
=> Cancel pointer down when out of game

packages/replay-starter-js/package.json, packages/replay-starter-ts/package.json
This replaces https://github.com/edbentley/replay-starter-js/pull/1
=> Starter packages: Use webpack in dev mode when running server

packages/replay-web/src/__tests__/replay-web.test.ts, packages/replay-web/src/__tests__/utils.ts, packages/replay-web/src/draw.ts, packages/replay-web/src/index.ts
Fixes #5 and audio pause / init bugs.
=> Web assets errors

packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/core.ts
Ensure `updateState` callbacks are called in between `loop` and `render`.
=> Core: Run updateState before render

dev-game/package-lock.json, dev-game/package.json, packages/replay-starter-js/package-lock.json, packages/replay-starter-js/package.json, packages/replay-starter-ts/package-lock.json, packages/replay-starter-ts/package.json, packages/replay-starter-ts/web/webpack.config.js
Also avoids webpack reporting test file errors in replay-starter
=> Upgrade webpack-dev-server

website/src/pages/games/made-with-replay.json
Hi Ed,
I was looking for a long time for a game engine with similar concepts as React, so I was very excited when I found Replay. I wanted to try it immediately and therefore I created this small game. It was very good developer experience. Keep up the good work.
Thank you.
Best regards,
Vladimir Pajic
=> Add sloops game

packages/replay-starter-js/package.json, packages/replay-starter-js/web/webpack.config.js, packages/replay-starter-ts/package.json, packages/replay-starter-ts/web/webpack.config.js
Fixes the [Codesandbox templates](https://codesandbox.io/s/github/edbentley/replay-starter-ts) linked to in the docs.
=> Fix replay-starter for Codesandbox

packages/replay-web/src/index.ts
Small change that affected iOS.
=> Web: resume audio context if suspended

website/docs/tutorial/1.md
https://github.com/edbentley/replay/issues/58
=> Fix spelling #58

packages/replay-core/src/core.ts, packages/replay-core/src/sprite.ts, website/docs/sprites.md
It can be useful to access this in other methods, especially `render`.
=> Add getState to all Sprite methods

dev-game/package.json, dev-game/tsconfig.json, packages/replay-swift/Replay/Sources/Replay/ReplayViewController.swift, packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift, packages/replay-swift/Replay/Tests/ReplayTests/ReplayTests.swift, packages/replay-swift/src/index.ts, packages/replay-swift/src/renderCanvas.ts, packages/replay-swift/src/types.d.ts, packages/replay-swift/test-game/package.json, packages/replay-swift/test-game/src/index.ts, packages/replay-swift/test-game/tsconfig.json, packages/replay-swift/test-game/webpack.swift.js, packages/replay-swift/tsconfig.json, packages/replay-swift/webpack.swift.js, website/docs/ios.md
This PR allows async messages to pass between JS game code and Swift code for users. It's a bit hacky with globals, but hides all of that with a clean Promise interface for users.
It's useful for things like in-app purchases and notifications which need to be accessed with Swift APIs.
=>  Swift / JS bridge

packages/replay-swift/Replay/Sources/Replay/ReplayClipboardManager.swift, packages/replay-swift/Replay/Sources/Replay/ReplayStorageProvider.swift, packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift, packages/replay-swift/Replay/Tests/ReplayTests/ReplayTests.swift, packages/replay-swift/src/renderCanvas.ts, packages/replay-swift/test-game/src/index.ts, packages/replay-web/src/device.ts, packages/replay-web/src/index.ts
This uses native clipboard features to avoid errors using clipboard in iOS webviews.
=> Use native clipboard on iOS

packages/replay-core/src/device.ts, packages/replay-text-input/src/__tests__/web.test.ts, packages/replay-web/jest-setup.js, packages/replay-web/src/__tests__/device.test.ts, packages/replay-web/src/__tests__/utils.ts, packages/replay-web/src/device.ts, website/docs/device.md
Adds `playbackRate` field to set audio speed when played.
=> Audio playback rate

.eslintrc.js, CONTRIBUTING.md, packages/replay-core/src/__benchmarks__/replay-core.benchmark.ts, packages/replay-core/src/__benchmarks__/utils.ts, packages/replay-core/src/core.ts, packages/replay-core/tsconfig.json
These benchmarks add a way to test the performance and memory usage of replay-core between commits using the [replay-benchmarks](https://github.com/edbentley/replay-benchmarks) repo.
=> Benchmarks

packages/replay-core/src/__benchmarks__/utils.ts, packages/replay-core/src/__tests__/replay-core.test.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/device.ts, packages/replay-test/src/__tests__/replay-test.test.ts, packages/replay-test/src/index.ts, packages/replay-web/jest-setup.js, packages/replay-web/src/__tests__/device.test.ts, packages/replay-web/src/device.ts, packages/replay-web/src/index.ts, website/docs/device.md
This (finally!) implements #36
* getStatus
* getVolume / setVolume
* getDuration
=> Additional audio API methods

packages/replay-swift/Replay/Sources/Replay/Html.swift, packages/replay-swift/Replay/Sources/Replay/ReplayViewController.swift, packages/replay-swift/Replay/Sources/Replay/ReplayWebView.swift, packages/replay-swift/Replay/Sources/Replay/Resources/index.html, packages/replay-swift/Replay/Tests/ReplayTests/ReplayTests.swift, packages/replay-web/src/__tests__/draw.test.ts, packages/replay-web/src/draw.ts, packages/replay-web/src/index.ts, website/docs/android.md, website/docs/ios.md
This addresses https://github.com/edbentley/replay/issues/53, canvas shapes and text should be looking nice and sharp now. @ejb 
Also supports custom fonts by being able to set your own CSS styles on iOS.
=> Canvas DPI and iOS custom styles

packages/replay-core/src/device.ts, packages/replay-test/src/__tests__/replay-test.test.ts, packages/replay-test/src/index.ts, packages/replay-web/src/device.ts, website/docs/device.md
Expands `setVolume` to allow for fade in and out effects. @ejb
=> Add fading to setVolume

packages/replay-core/src/core.ts, packages/replay-web/src/__tests__/draw.test.ts, packages/replay-web/src/draw.ts, packages/replay-web/src/index.ts, website/docs/top-level-game.md
Saves an additional drawing call if devs want to change the background colour.
=> Add backgroundColor game prop

dev-game/android/.idea/compiler.xml, dev-game/android/.idea/gradle.xml, dev-game/android/.idea/jarRepositories.xml, dev-game/android/.idea/misc.xml, dev-game/android/app/build.gradle, dev-game/android/build.gradle, dev-game/android/gradle/wrapper/gradle-wrapper.properties, packages/replay-android/android-library/.idea/gradle.xml, packages/replay-android/android-library/replay-android/build.gradle, packages/replay-starter-js/android/.idea/compiler.xml, packages/replay-starter-js/android/.idea/gradle.xml, packages/replay-starter-js/android/.idea/jarRepositories.xml, packages/replay-starter-js/android/.idea/misc.xml, packages/replay-starter-js/android/app/build.gradle, packages/replay-starter-js/android/build.gradle, packages/replay-starter-js/android/gradle/wrapper/gradle-wrapper.properties, packages/replay-starter-ts/android/.idea/compiler.xml, packages/replay-starter-ts/android/.idea/gradle.xml, packages/replay-starter-ts/android/.idea/jarRepositories.xml, packages/replay-starter-ts/android/.idea/misc.xml, packages/replay-starter-ts/android/app/build.gradle, packages/replay-starter-ts/android/build.gradle, packages/replay-starter-ts/android/gradle/wrapper/gradle-wrapper.properties
=> Upgrade gradle version

packages/replay-android/android-library/replay-android/src/main/java/com/replay/android/ReplayActivity.kt
Ensures the status bar autohides when tapped on.
=> Android: auto hide status bars when they reappear

packages/replay-core/src/__benchmarks__/utils.ts, packages/replay-core/src/__tests__/utils.ts, packages/replay-core/src/device.ts, packages/replay-test/src/index.ts, packages/replay-web/src/__tests__/replay-web.test.ts, packages/replay-web/src/device.ts, packages/replay-web/src/index.ts, website/docs/device.md, website/docs/web.md
This adds a `resolution` field to device to allow the resolution to be adjusted in-game.
=> Add resolution to device
